import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docs: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
        title: 'Getting Started',
        slug: '/category/getting-started',
        keywords: ['how-to'],
      },
      items: [
        'getting-started/installation',
        'getting-started/your-first-synchronization',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: ['guides/styling-notion-page', 'guides/using-equations'],
    },
    {
      type: 'category',
      label: 'Advanced Guides',
      items: [
        'advanced-guides/architecture',
        'advanced-guides/cli-commands',
        'advanced-guides/programmatic-usage',
      ],
    },
  ],

  api: [{ type: 'autogenerated', dirName: 'api' }],
};

export default sidebars;
