name: Publish package to npm

on:
  release:
    types: [published]

jobs:

  tests:
    uses: ./.github/workflows/tests.yaml

  publish-documentation:
    permissions:
      pages: write
      id-token: write
    uses: './.github/workflows/deploy-documentation.yaml'
    needs:
      - tests

  publish-package:
    permissions:
      contents: write
    needs:
      - tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.RELEASE_MANAGEMENT_DEPLOY_KEY_PRV }}
          persist-credentials: true
          ref: master

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: 'https://registry.npmjs.org'

      - name: Update package version to ${{ github.event.release.tag_name }}
        run: |

          git config --local user.email "mk-notes[bot]@mk-notes.io"
          git config --local user.name "mk-notes[bot]"

          echo "Updating package to version $PACKAGE_VERSION"
          yarn version --new-version $PACKAGE_VERSION
        env:
          PACKAGE_VERSION: ${{ github.event.release.tag_name }}

      - name: Push to master branch
        uses: ad-m/github-push-action@master
        with:
          branch: master
          force_with_lease: true

      - run: yarn install --frozen-lockfile

      - run: yarn build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

